imzML partitioner
aitorarjona/cloud-native-datasets pull request #2
Opened 2022-12-02 13:50 UTC by locotron

2022-12-02 21:48 UTC, aitorarjona commented on dataplug/metabolomics/imzML.py
> +    slices = []
convert to list comprehension

2022-12-02 21:49 UTC, aitorarjona requested changes
remove sample files or find some smaller files ~10KB max

2022-12-02 21:49 UTC, aitorarjona commented on dataplug/metabolomics/imzML.py
> +        mzArray = []
convert to list comprehension

2022-12-03 11:06 UTC, locotron commented on dataplug/metabolomics/imzML.py
> +        mzArray = []
If converted to list comprehension it will become List[np.buffer] instead of np.array.

2023-01-11 10:35 UTC, closed without merging